"""
Django settings for BallBearingProject project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
TEMPLATE_DIR= os.path.join(BASE_DIR, 'templates')
# TEMPLATE_LOADERS = ( 'django.template.loaders.filesystem.Loader',
#                      'django.template.loaders.app_directories.Loader',
#                      'django.template.loaders.eggs.Loader', )

# LOCALE_PATHS = (os.path.join(BASE_DIR , 'BallbearingSite\locale'),
# STATIC_DIR=os.path.join(BASE_DIR,"static")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x**b4@-@a^whs$)#-j$w5*hj9fizpbqmbmfj-5*(wyax3o4^jg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Application definition

INSTALLED_APPS = (
    'BallbearingSite',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'import_export',
    #ckeditor fields
    'ckeditor',
    'ckeditor_uploader',
    'ajax_select',
)

MIDDLEWARE_CLASSES = (
   'django.contrib.sessions.middleware.SessionMiddleware',

   'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

)


ROOT_URLCONF = 'BallBearingProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        # 'loaders': [
        #         'admin_tools.template_loaders.Loader',
        #         ('django.template.loaders.cached.Loader', [
        #             'django.template.loaders.filesystem.Loader',
        #             'django.template.loaders.app_directories.Loader',
        #         ]),
        #     ],
        },
    },
]

WSGI_APPLICATION = 'BallBearingProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'

MEDIA_URL  = '/media/'
MEDIA_ROOT = 'media/'
# STATICFILES_DIRS=[
# STATIC_DIR,
# ]
# STATICFILES_DIRS=(
#     os.path.join(BASE_DIR,'BallbearingSite','static'),
#     )
LOGIN_URL='/BallbearingSite/user_login'

IMPORT_EXPORT_USE_TRANSACTIONS = True

#ckeditor settings
CKEDITOR_CONFIGS = {
    'default' :{
    'toolbar' :'Advance',
    },
}
#ckeditor configs
CKEDITOR_UPLOAD_PATH = MEDIA_ROOT + 'ck_uploads/'
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_MONIMAGE_FILES = True
